# HW01: Các câu lệnh Linux, Python

(Cập nhật lần cuối 06/11/2025)

Họ tên: Trần Hoài Thiện Nhân

MSSV: 23127238

---

## Cách làm bài và nộp bài

&#9889; Bạn lưu ý là mình sẽ dùng chương trình hỗ trợ chấm bài nên bạn cần phải tuân thủ chính xác qui định mà mình đặt ra, nếu không rõ thì hỏi, chứ không nên tự tiện làm theo ý của cá nhân.

**Cách làm bài**

Bạn sẽ làm trực tiếp trên file notebook này. Đầu tiên, bạn điền họ tên và MSSV vào phần đầu file ở bên trên. Trong file, bạn làm bài ở những chỗ có ghi là:
```python
# YOUR CODE HERE
raise NotImplementedError()
```
hoặc đối với những phần code không bắt buộc thì là:
```python
# YOUR CODE HERE (OPTION)
```
hoặc đối với markdown cell thì là:
```markdown
YOUR ANSWER HERE
```
Tất nhiên, khi làm thì bạn xóa dòng `raise NotImplementedError()` đi.
Đối những phần yêu cầu code thì thường ở ngay phía dưới sẽ có một (hoặc một số) cell chứa các bộ test để giúp bạn biết đã code đúng hay chưa; nếu chạy cell này không có lỗi gì thì có nghĩa là qua được các bộ test. Trong một số trường hợp, các bộ test có thể sẽ không đầy đủ; nghĩa là, nếu không qua được test thì là code sai, nhưng nếu qua được test thì chưa chắc đã đúng hoàn toàn.

Trong khi làm bài, bạn có thể cho in ra màn hình, tạo thêm các cell để test. Nhưng khi nộp bài thì bạn xóa các cell mà bạn tự tạo, xóa hoặc comment các câu lệnh in ra màn hình. Bạn lưu ý <font color=red>không được tự tiện xóa các cell hay sửa code của Thầy</font> (trừ những chỗ được phép sửa như đã nói ở trên).

Bạn cố gắng giữ cho code rõ ràng, ngăn nắp: đặt tên biến gợi ý, comment ở những chỗ cần comment, giữ cho một dòng code không quá dài (vì nếu không thì người đọc sẽ phải mất công scroll, bạn có thể dùng qui tắc: một dòng code chỉ nên có tối đa là 79 ký tự). 

Trong khi làm bài, thường xuyên `Ctrl + S` để lưu lại bài làm của bạn, tránh mất mát thông tin.


*Nên nhớ mục tiêu chính ở đây là <font color=green>học, học một cách chân thật</font>. Bạn có thể thảo luận ý tưởng với bạn khác, nhưng <font color=green>code và bài làm phải là của bạn, dựa trên sự hiểu thật sự của bạn</font>. <font color=red>Nếu vi phạm thì sẽ bị 0 điểm cho toàn bộ môn học.</font>*

**Cách nộp bài**

Khi chấm bài, đầu tiên mình sẽ chọn `Kernel` - `Restart & Run All` để restart và chạy tất cả các cell trong notebook của bạn; do đó, trước khi nộp bài, bạn nên chạy thử `Kernel` - `Restart & Run All` để đảm bảo mọi chuyện diễn ra đúng như mong đợi.

Sau đó, bạn tạo thư mục nộp bài theo cấu trúc sau:
- Thư mục `MSSV` (vd, nếu bạn có MSSV là 1234567 thì bạn đặt tên thư mục là `1234567`)
    - File `HW01.ipynb` (không cần nộp các file khác)

Cuối cùng, bạn nén thư mục `MSSV` này lại và nộp ở link trên moodle. <font color=red>Bạn lưu ý tuân thủ chính xác qui định nộp bài.</font>

---

## Môi trường code

Ta thống nhất trong môn này:
- Code trên môi trường Linux (bạn đã setup ở HW0)
- Dùng Jupyter Notebook hoặc Jupyter Lab để code file .ipynb. Lưu ý: bạn <font color=red>không dùng Google Colab</font>, vì Google Colab có thể xóa một số thông tin meta mà chương trình hỗ trợ chấm bài của mình đã tạo trong file bài tập
- Dùng phiên bản các package như trong file "min_ds-env.yml" (bạn xem trong HW0 cách dùng Conda để tạo môi trường code từ file .yml và cách kích hoạt môi trường này sau khi đã tạo)

In [1]:
import sys
sys.executable

'/home/thtn/anaconda3/envs/min_ds-env/bin/python'

Nếu không có vấn đề gì thì file chạy python sẽ là file của môi trường code "min_ds-env".

Trong bài này, ngoài Git & Jupyter Notebook/Lab thì bạn chỉ dùng Python, không dùng các thư viện khác như Numpy, Pandas, ... Trong Python, khi đọc/ghi file csv thì bạn cũng không được dùng các thư viện hỗ trợ như thư viện `csv`.

---

## Import các thư viện cần thiết

In [2]:
import datetime
# YOUR CODE HERE (OPTION)

---

## Thu thập dữ liệu (3.5đ)

Trong bài tập này, bạn sẽ lấy dữ liệu log của [thùng chứa nbdime](https://github.com/namlnhut/nbdime). Nbdime là công cụ giúp Git có thể diff và merge file Notebook một cách phù hợp (thay vì chỉ coi như là một file text thông thường). Link mình cung cấp không phải là link đến thùng chứa gốc của nbdime mà là thùng chứa mình "fork" (đại khái là tạo ra một bản copy) từ thùng chứa gốc. Lý do: mình muốn cố định lại dữ liệu log để có thể cung cấp các bộ test để bạn phần nào biết là đã code đúng hay chưa (còn nếu dùng thùng chứa gốc thì dữ liệu log có thể sẽ thay đổi trong vài ngày tới, các bộ test lúc đó có thể sẽ không còn đúng nữa).

Để có thể lấy dữ liệu log thì việc đầu tiên bạn cần làm ở cell bên dưới là: 

- Dùng câu lệnh Git để clone thùng chứa về; bạn clone vào một thư mục cùng cấp với file notebook này. <font color=gray>Gợi ý: trong Jupyter Notebook, ở code cell, bạn có thể thực hiện một câu lệnh Linux (bao gồm câu lệnh Git) bằng cách thêm dấu ! ở đầu.</font>
- Sau đó, để xem thử thư mục vừa clone có nặng không, bạn tính dung lượng tổng cộng của thư mục này và lưu vào biến `repo_size` (`repo_size` là một con số, đơn vị là MB); ta thống nhất: (i) dùng cờ `--apparent-size` khi dùng câu lệnh `du`, (ii) code chỉ cần chạy đúng với thùng chứa cụ thể này. <font color=gray>Gợi ý: trong Jupyter Notebook, bạn có thể gán kết quả của câu lệnh Linux vào biến Python.</font> \
@ Các bạn dùng Mac: trong Mac thì mình nghe nói là câu lệnh `du` không có cờ `--apparent-size` (do câu lệnh `du` của Mac là bản BSD, còn của Linux là bản GNU); bạn có thể xem thử cách cài câu lệnh `du` bản GNU ở [video này](https://youtu.be/VGgTmxXp7xQ?t=894) (trong video là nói về câu lệnh `grep` nhưng mình nghĩ cũng sẽ tương tự với câu lệnh `du`).

In [3]:
# YOUR CODE HERE
!git clone https://github.com/namlnhut/nbdime.git
size_str = !du --apparent-size -s nbdime | cut -f1
repo_size = float(size_str[0]) / 1024

# result = !du -sh --apparent-size nbdime
# size_str = result[0].split()[0]
# repo_size = float(size_str.replace('M', ''))

print(f"\nRepository size: {repo_size} MB")

Cloning into 'nbdime'...
remote: Enumerating objects: 14752, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 14752 (delta 9), reused 11 (delta 5), pack-reused 14720 (from 1)
Receiving objects: 100% (14752/14752), 14.47 MiB | 2.52 MiB/s, done.
Resolving deltas: 100% (10602/10602), done.

Repository size: 20.96875 MB


Sau khi đã clone thùng chứa về, việc kế tiếp của bạn là dùng các câu lệnh Linux (trong đó có các câu lệnh Git) và Python để lấy dữ liệu log rồi lưu xuống file "log.tsv" (định dạng tsv tương tự như csv nhưng các giá trị được cách nhau bởi tab). Để dễ hình dung, bạn có thể dùng Jupyter Lab để mở xem file kết quả đúng "correct_log.tsv" mà mình cung cấp. Như bạn có thể thấy, mỗi dòng ứng với một commit (không tính dòng đầu - dòng chứa các tên cột) và gồm các thông tin:
- "Id" là id (hash) dạng viết gọn của commit
- "ParentIds" là id dạng viết gọn của (các) commit cha
- "AuthorName" là tên của tác giả
- "AuthorEmail" là email của tác giả
- "AuthorDate" là ngày tác giả thực hiện commit, ngày được format theo chuẩn RFC2822 (xem phần gợi ý ở bên dưới để biết cách lấy ngày theo format này) 
- "Subject" là tựa đề của message (message tương tự như email, ngoài phần "subject" thì có thể có thêm phần "body"; ở đây ta chỉ lấy phần "subject")
- "ChangedFiles": các file bị thay đổi, nếu có nhiều file thì các file được phân tách bởi dấu phẩy

Tại sao mình dùng định dạng tsv thay vì csv? Vì dấu phẩy nhiều khả năng là sẽ có trong phần "subject" của message. Tab ít khả năng sẽ có hơn, nhưng nếu có thì bạn hãy thay bằng bốn khoảng trắng.

<font color=gray>Gợi ý cho phần này:</font> 
- <font color=gray>Bạn có thể xem thêm về câu lệnh `git log` [ở đây](https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History)</font>
- <font color=gray>Khi ở Notebook, bạn thử `cd` đến thư mục clone rồi `pwd` xem? Kết quả như vậy là vì khi thực hiện một dòng lệnh Linux ở Notebook thì Notebook sẽ tạo ra một terminal tạm thời để thực thi dòng lệnh đó trong phút chốc. Như vậy, câu lệnh `cd` vẫn là có `cd` đến thư mục clone nhưng là ở terminal tạm thời; khi câu lệnh `cd` chạy xong thì terminal tạm thời này sẽ được đóng và ta vẫn ở thư mục mà hiện chứa file Notebook. Để có thể `cd` rồi `pwd` thì một cách là ghi 2 câu lệnh này trên một dòng và cách nhau bởi `&&`; lúc này thì cả 2 câu lệnh sẽ được thực thi trên cùng một terminal</font>

In [4]:
# YOUR CODE HERE
log_output = !cd nbdime && git log --name-only --date=rfc --pretty=format:"%h%x09%p%x09%an%x09%ae%x09%ad%x09%s"

lines = []
current_commit = None

for line in log_output:
    line = line.strip()
    if not line:
        continue
    
    if '\t' in line:
        parts = line.split('\t')
        if len(parts) == 6:
            current_commit = {
                'Id': parts[0],
                'ParentIds': parts[1],
                'AuthorName': parts[2],
                'AuthorEmail': parts[3],
                'AuthorDate': parts[4],
                'Subject': parts[5].replace('\t', '    '),
                'ChangedFiles': []
            }
            lines.append(current_commit)
    else:
        # It's a changed file
        if current_commit is not None:
            current_commit['ChangedFiles'].append(line)

with open('log.tsv', 'w') as f:
    f.write('Id\tParentIds\tAuthorName\tAuthorEmail\tAuthorDate\tSubject\tChangedFiles\n')
    for commit in lines:
        changed_files = ','.join(commit['ChangedFiles']) if commit['ChangedFiles'] else ''
        f.write(f"{commit['Id']}\t{commit['ParentIds']}\t{commit['AuthorName']}\t"
                f"{commit['AuthorEmail']}\t{commit['AuthorDate']}\t{commit['Subject']}\t"
                f"{changed_files}\n")

In [5]:
# TEST
file = open('log.tsv', 'r')
log = file.read()
file.close()
file = open('correct_log.tsv', 'r')
correct_log = file.read()
file.close()
assert log == correct_log

---

## Khám phá dữ liệu

### Dữ liệu có bao nhiêu dòng và bao nhiêu cột? (0.5đ)

Đầu tiên, bạn sẽ đọc dữ liệu từ file "log.tsv" (nếu phần thu thập dữ liệu bạn làm chưa đúng thì bạn có thể đọc từ file "correct_log.tsv" mà mình đã cung cấp). Bạn lưu kết quả đọc được vào biến `cols`. Biến `cols` là một dictionary, trong đó mỗi phần tử ứng với một cột, key là chuỗi ứng với tên cột, value là list chứa các giá trị của cột (mỗi giá trị bạn cứ tạm để kiểu dữ liệu là chuỗi).

Kế tiếp, từ biến `cols`, bạn sẽ tính số dòng và số cột, rồi lần lượt lưu vào hai biến là `num_rows` và `num_cols`.

In [ ]:
# YOUR CODE HERE
def read_log_tsv(filepath):
    cols = {
        'Id': [], 
        'ParentIds': [], 
        'AuthorName': [], 
        'AuthorEmail': [],
        'AuthorDate': [], 
        'Subject': [], 
        'ChangedFiles': []
    }
    
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    header = lines[0].strip().split('\t')
    for line in lines[1:]:
        values = line.strip().split('\t')
        if len(values) < 6:
            continue
        cols['Id'].append(values[0])
        cols['ParentIds'].append(values[1])
        cols['AuthorName'].append(values[2])
        cols['AuthorEmail'].append(values[3])
        cols['AuthorDate'].append(values[4])
        cols['Subject'].append(values[5])
        cols['ChangedFiles'].append(values[6] if len(values) > 6 else '')
    return cols

cols = read_log_tsv('log.tsv')
#cols = read_log_tsv('correct_log.tsv')

num_rows = len(cols['Id'])
num_cols = len(cols)

num_rows

2149

In [7]:
# TEST
assert num_rows == 2149
assert num_cols == 7
assert set(cols.keys()) == set(['Id', 'ParentIds', 'AuthorName', 
                                'AuthorEmail', 'AuthorDate', 'Subject', 
                                'ChangedFiles'])
id_col_len = len(cols['Id'])
for col_name in cols:
    assert len(cols[col_name]) == id_col_len

### Mỗi dòng có ý nghĩa gì? Có vấn đề các dòng có ý nghĩa khác nhau không?

Mỗi dòng ứng với một commit. Có vẻ không có dòng nào "lạc loài" (nghĩa là không có vấn đề các dòng có ý nghĩa khác nhau).

### Dữ liệu có các dòng bị lặp không? (0.25đ)

Có lẽ là không có. Để chắc ăn thì một cách là ta có thể check cột "Id"; nếu cột "Id" không có giá trị bị lặp thì có thể kết luận là không có dòng bị lặp. Bạn sẽ làm vụ này và lưu kết quả check vào biến `duplicated_id`; biến này bằng True nếu cột "Id" có giá trị lặp và bằng False nếu ngược lại.

In [8]:
# YOUR CODE HERE
id_set = set()
duplicated_id = False
for id_val in cols['Id']:
    if id_val in id_set:
        duplicated_id = True
        break
    id_set.add(id_val)

In [9]:
# TEST
assert duplicated_id == False

### Mỗi cột có ý nghĩa gì?

Vụ này mình đã nói lúc thu thập dữ liệu. Ở đây, mình ghi lại một lần nữa:

- "Id" là id (hash) dạng viết gọn của commit
- "ParentIds" là id dạng viết gọn của (các) commit cha
- "AuthorName" là tên của tác giả
- "AuthorEmail" là email của tác giả
- "AuthorDate" là ngày tác giả thực hiện commit
- "Subject" là tựa đề của message (message tương tự như email, ngoài phần "subject" thì có thể có thêm phần "body"; ở đây ta chỉ lấy phần "subject")
- "ChangedFiles": các file bị thay đổi, nếu có nhiều file thì các file được phân tách bởi dấu phẩy

### Mỗi cột hiện đang có kiểu dữ liệu gì? Có cột nào có kiểu dữ liệu chưa phù hợp để có thể xử lý tiếp không?

- Các cột "Id", "ParentIds", "AuthorName", "AuthorEmail", "Subject": kiểu dữ liệu dạng chuỗi là đúng rồi
- Cột "ChangedFiles": hmm ... có lẽ tạm thời ta vẫn để dạng chuỗi, có gì cần thì ta sẽ xử lý sau
- Cột "AuthorDate": cần chuyển từ kiểu dữ liệu dạng chuỗi sang datetime; để có thể tiếp tục khám phá tiếp thì ngay sau đây bạn sẽ tiền xử lý vụ này luôn

---

## Tiền xử lý (0.5đ)

Ở đây, bạn sẽ chuyển cột "AuthorDate" từ dạng chuỗi sang datetime. <font color=gray>Gợi ý: bạn xem [document](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) để biết cách truyền format phù hợp cho hàm `strptime`.</font>

In [10]:
# YOUR CODE HERE
for i in range(len(cols['AuthorDate'])):
    cols['AuthorDate'][i] = datetime.datetime.strptime(
        cols['AuthorDate'][i], 
        '%a, %d %b %Y %H:%M:%S %z'
    )

print(f"First date: {cols['AuthorDate'][0]}")

First date: 2025-10-09 11:32:46+02:00


In [11]:
# TEST
assert type(cols['AuthorDate'][0]) == datetime.datetime
assert cols['AuthorDate'][0] == datetime.datetime(2025, 10, 9, 11, 32, 46, 
            tzinfo=datetime.timezone(datetime.timedelta(seconds=7200)))

---

## Khám phá dữ liệu (tiếp tục)

### Với mỗi cột có kiểu dữ liệu dạng số (numeric) và dạng datetime, các giá trị được phân bố như thế nào? (0.5đ)

Ở đây thì không có cột dạng số, chỉ có một cột dạng datetime là cột "AuthorDate".

Đầu tiên, bạn tính tỉ lệ % các giá trị thiếu của cột "AuthorDate". <font color=gray>Gợi ý: không cần code, có thể lập luận dựa vào kết quả khi chuyển cột "AuthorDate" từ dạng chuỗi sang datetime ở bên trên.</font>

YOUR ANSWER HERE

When converting the "AuthorDate" column from string to datetime above, I did not handle the possibility that the value of the "AuthorDate" column was an empty string, and the code did not report an error when executing the `datetime.datetime.strptime` function (when the string is empty, it will be different from the format I defined $\to$ error $\to$ report an error). So all commits have an author date.

Tiếp theo, bạn tính min và max của cột "AuthorDate", rồi lần lượt lưu vào hai biến `author_date_min` và `author_date_max`.

In [12]:
# YOUR CODE HERE
author_date_min = min(cols['AuthorDate'])
author_date_max = max(cols['AuthorDate'])

In [13]:
# TEST
assert author_date_min == datetime.datetime(2015, 11, 9, 13, 13, 28, 
            tzinfo=datetime.timezone(datetime.timedelta(seconds=3600)))
assert author_date_max == datetime.datetime(2025, 10, 9, 11, 32, 46, 
            tzinfo=datetime.timezone(datetime.timedelta(seconds=7200)))

Hmm ... Min và max của cột "AuthorDate" không có gì bất thường.

### Với mỗi cột có kiểu dữ liệu dạng phân loại (categorical), các giá trị được phân bố như thế nào? (1.75đ)

Các cột dạng phân loại là các cột mà không phải là cột "AuthorDate". Bạn sẽ lưu thông tin của các cột này vào biến `cate_col_profiles`. Biến này là một dictionary, trong đó mỗi phần tử ứng với một cột dạng phân loại, key là tên cột, value là list gồm: tỉ lệ % giá trị thiếu, số lượng các giá trị khác nhau (không tính giá trị thiếu), set chứa các giá trị khác nhau (không bao gồm giá trị thiếu).

In [14]:
# YOUR CODE HERE
def get_profiles(col_values):
    total = len(col_values)
    missing = sum(1 for v in col_values if v == '')
    unique_vals = set()
    for v in col_values:
        if v != '':
            unique_vals.add(v)
    missing_ratio = (missing / total) * 100
    return [missing_ratio, len(unique_vals), unique_vals]

cate_col_profiles = {}
categorical_cols = ['Id', 'ParentIds', 'AuthorName', 'AuthorEmail', 'Subject', 'ChangedFiles']
for col in categorical_cols:
    cate_col_profiles[col] = get_profiles(cols[col])

In [15]:
# TEST
assert set(cate_col_profiles.keys()) == {'AuthorEmail', 'AuthorName', 
                                         'ChangedFiles', 'Id', 
                                         'ParentIds', 'Subject'}
for col_name, col_profile in cate_col_profiles.items():
    assert len(col_profile) == 3
    assert len(col_profile[2]) == col_profile[1]
assert round(cate_col_profiles['ParentIds'][0], 3) == 0.047
assert round(cate_col_profiles['ChangedFiles'][0], 3) == 15.914
assert cate_col_profiles['ParentIds'][1] == 2029
assert cate_col_profiles['ChangedFiles'][1] == 934

In [16]:
# TEST (BY EYES)
print(f"{'ColName':12} {'Miss(%)':7} {'NumDifVals':10} {'SomeVals'}")
for col_name, col_profile in cate_col_profiles.items():
    print(f'{col_name:12} {col_profile[0]:<7.3f} {col_profile[1]:<10} {col_profile[2].__repr__()[:34]+"...":<}')

ColName      Miss(%) NumDifVals SomeVals
Id           0.000   2149       {'a0726e5', '9560159', '5a6ba9b', ...
ParentIds    0.047   2029       {'a0726e5', '20e07f4 58c5197', 'e4...
AuthorName   0.000   55         {'Dean P', 'Cory Gwin', 'David Bau...
AuthorEmail  0.000   58         {'stslve@amazon.com', 's.shanabroo...
Subject      0.000   2058       {'Git diff api handles deleted/add...
ChangedFiles 15.914  934        {'nbdime/merging/decisions.py,nbdi...


Bạn quan sát kết quả in ra ở trên (tạm thời chưa để ý đến cột "Miss(%)") và cho biết có gì bất thường không? Hay mọi thứ đều bình thường? Cho mình biết tại sao bạn lại kết luận như vậy.

YOUR ANSWER HERE

Everything is normal:
- `Id`           : 2149 unique $\to$ ok. It equals with the number of row above (each commit has unique ID)
- `ParentIds`    : 2029 unique $\to$ ok. Some commits have same parent(s), normal in Git
- `AuthorName`   : small number of unique values $\to$ ok. Few contributors and they can have the same name
- `AuthorEmail`  : small number of unique values $\to$ ok. Few contributors
- `Subject`      : many unique $\to$ ok. Each commit has different message and sometime, 2 contributions written the same subject for different subjects
- `ChangedFiles` : 934 unique $\to$ ok. Many commits change same set of files or these are merge commits

Kế tiếp, bạn hãy cho in ra các dòng mà có giá trị thiếu (in sao là tùy bạn, miễn là dễ nhìn). Sau đó, bạn hãy quan sát các dòng này để xem tại sao lại bị thiếu (trong trường hợp, bạn không biết tại sao thì cứ ghi nhận là không biết tại sao).

In [17]:
# YOUR CODE HERE
print(f"{'Id':8} {'AuthorDate':20} {'ChangedFiles'}")
print("-" * 80)
for i in range(num_rows):
    if cols['ChangedFiles'][i] == '':
        date_str = cols['AuthorDate'][i].strftime("%Y-%m-%d %H:%M")
        print(f"{cols['Id'][i]:8} {date_str:20} {cols['ChangedFiles'][i]}")

Id       AuthorDate           ChangedFiles
--------------------------------------------------------------------------------
606b6fd  2025-10-09 11:32     
ecf8996  2025-10-08 13:39     
3dcdce3  2023-11-10 19:18     
2f54b80  2023-11-10 16:31     
e56e9fa  2023-11-06 18:11     
c1ea9b9  2023-11-01 12:17     
3c064bd  2023-10-16 16:09     
e6d2e28  2023-09-27 11:05     
2db03bc  2023-09-27 10:53     
ac5eb35  2023-09-25 10:17     
da240a2  2023-09-18 10:42     
43168fc  2023-09-08 11:52     
b1804b1  2023-04-30 16:20     
691b9c8  2023-04-22 11:28     
9fbfd46  2023-03-24 23:20     
50c9347  2023-03-24 22:50     
2da614b  2023-01-15 17:22     
0d57918  2023-01-15 17:09     
fe11ad5  2023-01-14 16:10     
f503763  2022-11-24 14:42     
4bc7ae2  2022-07-05 17:29     
ecded88  2022-06-19 10:48     
2db0b44  2022-06-19 10:46     
fa4e2a3  2022-04-18 10:42     
bbf621e  2022-04-09 05:33     
fc31fbb  2022-02-28 10:52     
17d103c  2021-11-03 11:51     
e44a5cc  2021-10-25 23:51     
f16d448 

YOUR ANSWER HERE

These are **merge commits** (e.g., "Merge pull request..."). Git does not list changed files in `--name-only` for merge commits.

---

## Đưa ra câu hỏi có ý nghĩa cần trả lời

Sau khi khám phá dữ liệu, ta đã hiểu hơn về dữ liệu. Bây giờ, ta hãy xem thử có câu hỏi nào có ý nghĩa mà có thể được trả lời bằng dữ liệu này không.

Các câu hỏi có thể có là: 
- *Câu hỏi 1: trong năm 2021, ai là người có nhiều commit nhất, ai là người có nhiều commit nhì, ...?* \
Tìm câu trả lời cho câu hỏi này để làm gì? \
Hmm ... Chẳng hạn để khen thưởng
- *Câu hỏi 2: commit nào là commit cuối cùng (xét trên "AuthorDate") đã thay đổi file "nbdime/webapp/templates/difftool.html"?* \
Tìm câu trả lời cho câu hỏi này để làm gì? \
Hmm ... Chẳng hạn để đổ tội cho tác giả của commit đó ;-)

---

## Tiền xử lý (nếu cần) + phân tích dữ liệu để trả lời cho câu hỏi 1 (1đ)

Nhắc lại câu hỏi 1: *trong năm 2023, ai là người có nhiều commit nhất, ai là người có nhiều commit nhì, ...?*

Bạn sẽ lưu kết quả vào biến `wanted_people`. Biến này là một dictionary, mỗi phần tử ứng với một người mà có commit trong năm 2023, key là tên của người đó, value là số lượng commit của người đó. Dictionary này được sort theo value giảm dần.

In [18]:
# YOUR CODE HERE
wanted_people = {}
for i in range(num_rows):
    date = cols['AuthorDate'][i]
    if date.year == 2023:
        name = cols['AuthorName'][i]
        wanted_people[name] = wanted_people.get(name, 0) + 1

wanted_people = dict(sorted(wanted_people.items(), key=lambda x: x[1], reverse=True))

In [19]:
# TEST
correct_wanted_people = {'Vidar Tonaas Fauske': 62,
                         'Frédéric Collonval': 31,
                         'Florence Haudin': 18,
                         'github-actions[bot]': 14,
                         'fcollonval': 4,
                         'dependabot[bot]': 4,
                         'HaudinFlorence': 4,
                         'krassowski': 3,
                         'Michał Krassowski': 3,
                         'Chih-Hsuan Yen': 2,
                         'Angus Hollands': 1,
                         'Min RK': 1,
                         'Johan Mabille': 1,
                         'Saiwing Yeung': 1,
                         'Cory Gwin': 1}
assert wanted_people == correct_wanted_people

---

## Tiền xử lý (nếu cần) + phân tích dữ liệu để trả lời cho câu hỏi 2 (2đ)

Nhắc lại câu hỏi 2: *commit nào là commit cuối cùng (xét trên "AuthorDate") đã thay đổi file "nbdime/webapp/templates/difftool.html"?*

Ta thống nhất: không xét các commit "merge pull request" vì các commit này không có thông tin về "ChangedFiles".

Bạn lưu kết quả vào biến `wanted_commit`. Biến này là một dictionary, trong đó mỗi phần tử ứng với một thông tin của commit, key là tên cột, value là giá trị tương ứng.

In [20]:
# YOUR CODE HERE
target_file = "nbdime/webapp/templates/difftool.html"
candidates = []

for i in range(num_rows):
    changed = cols['ChangedFiles'][i]
    if changed == '':
        continue
    if target_file in changed.split(','):
        parent_ids = cols['ParentIds'][i]
        subject = cols['Subject'][i]
        if ' ' in parent_ids and subject.startswith("Merge pull request"):
            continue
        candidates.append({
            'Id': cols['Id'][i],
            'ParentIds': cols['ParentIds'][i],
            'AuthorName': cols['AuthorName'][i],
            'AuthorEmail': cols['AuthorEmail'][i],
            'AuthorDate': cols['AuthorDate'][i],
            'Subject': cols['Subject'][i],
            'ChangedFiles': cols['ChangedFiles'][i]
        })

# Find the latest by AuthorDate
if candidates:
    wanted_commit = max(candidates, key=lambda x: x['AuthorDate'])
else:
    wanted_commit = {}

wanted_commit

{'Id': 'd39f45a',
 'ParentIds': '8ebbc6e',
 'AuthorName': 'Frédéric Collonval',
 'AuthorEmail': 'fcollonval@users.noreply.github.com',
 'AuthorDate': datetime.datetime(2023, 10, 20, 23, 20, 31, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200))),
 'Subject': 'Do not collapse editor lines in single editor (#719)',
 'ChangedFiles': 'nbdime/webapp/templates/compare.html,nbdime/webapp/templates/diff.html,nbdime/webapp/templates/difftool.html,nbdime/webapp/templates/merge.html,nbdime/webapp/templates/mergetool.html,packages/nbdime/src/common/mergeview.ts,ui-tests/data/merge_test6/center.ipynb,ui-tests/data/merge_test6/left.ipynb,ui-tests/data/merge_test6/right.ipynb,ui-tests/package-lock.json,ui-tests/tests/nbdime-merge-test6.spec.ts,ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-linux.png,ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-win32.png'}

In [21]:
# TEST
correct_wanted_commit = {'Id': 'd39f45a',
 'ParentIds': '8ebbc6e',
 'AuthorName': 'Frédéric Collonval',
 'AuthorEmail': 'fcollonval@users.noreply.github.com',
 'AuthorDate': datetime.datetime(2023, 10, 20, 23, 20, 31, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200))),
 'Subject': 'Do not collapse editor lines in single editor (#719)',
 'ChangedFiles': 'nbdime/webapp/templates/compare.html,nbdime/webapp/templates/diff.html,nbdime/webapp/templates/difftool.html,nbdime/webapp/templates/merge.html,nbdime/webapp/templates/mergetool.html,packages/nbdime/src/common/mergeview.ts,ui-tests/data/merge_test6/center.ipynb,ui-tests/data/merge_test6/left.ipynb,ui-tests/data/merge_test6/right.ipynb,ui-tests/package-lock.json,ui-tests/tests/nbdime-merge-test6.spec.ts,ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-linux.png,ui-tests/tests/nbdime-merge-test6.spec.ts-snapshots/merge-test6-take-a-snapshot-at-opening-1-win32.png'}
assert wanted_commit == correct_wanted_commit